spring:
  freemarker:
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8

server:
  port: 80
  servlet:
    context-path: /jsonldapi
  tomcat:
    uri-encoding: UTF-8
    max-threads: 30

logging:
  config: classpath:logback.xml