spring:
  datasource:
    url: jdbc:sqlserver://battlecat.ddns.net:1433;DatabaseName=showcase
    username: amy
    password: amy
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    tomcat:
      max-wait: 15000
      max-active: 10
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        order_inserts: true
        order_updates: true
        jdbc: 
          batch_size: 100
          fetch_size: 100
          batch_versioned_data: true

server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 10

logging:
  config: classpath:logback.xml