spring:
  datasource:
    url: jdbc:sqlserver://socem1.uopnet.plymouth.ac.uk:1433;DatabaseName=COMP2001HK_WAo
    username: WAo
    password: RkpH901+
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    tomcat:
      max-wait: 15000
      max-active: 10
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        order_inserts: true
        order_updates: true
        jdbc: 
          batch_size: 100
          fetch_size: 100
          batch_versioned_data: true

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    max-threads: 30

logging:
  config: classpath:logback.xml